# Generated by Django 3.0.5 on 2020-11-23 13:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateTimeField()),
                ('subject', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=10)),
                ('memo', models.TextField()),
                ('color', models.CharField(choices=[('#FFFFFF', '白'), ('#1E90FF', '青'), ('#FF4500', '赤'), ('#32CD32', '緑'), ('#FFFF4A', '黄色')], default='#FFFFFF', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('url', models.TextField(blank=True)),
                ('memo', models.TextField(blank=True)),
                ('day_period', models.CharField(default='', help_text='ex) Mon1, Wed4', max_length=6)),
                ('color', models.CharField(choices=[('#FFFFFF', '白'), ('#1E90FF', '青'), ('#FF4500', '赤'), ('#32CD32', '緑'), ('#FFFF4A', '黄色')], default='#FFFFFF', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sat', models.BooleanField(default=False)),
                ('sun', models.BooleanField(default=False)),
                ('s1', models.TimeField(blank=True, default=None, null=True)),
                ('e1', models.TimeField(blank=True, default=None, null=True)),
                ('s2', models.TimeField(blank=True, default=None, null=True)),
                ('e2', models.TimeField(blank=True, default=None, null=True)),
                ('s3', models.TimeField(blank=True, default=None, null=True)),
                ('e3', models.TimeField(blank=True, default=None, null=True)),
                ('s4', models.TimeField(blank=True, default=None, null=True)),
                ('e4', models.TimeField(blank=True, default=None, null=True)),
                ('s5', models.TimeField(blank=True, default=None, null=True)),
                ('e5', models.TimeField(blank=True, default=None, null=True)),
                ('s6', models.TimeField(blank=True, default=None, null=True)),
                ('e6', models.TimeField(blank=True, default=None, null=True)),
                ('s7', models.TimeField(blank=True, default=None, null=True)),
                ('e7', models.TimeField(blank=True, default=None, null=True)),
                ('open_link', models.BooleanField(default=False)),
                ('period', models.IntegerField(choices=[(4, '4'), (5, '5'), (6, '6'), (7, '7')], default=4, validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(7)])),
            ],
        ),
    ]
